"use client";

/**
 * Loads the boneyard-js generated registry on the client side.
 *
 * The bones/ directory is generated by running:
 *   npm run bones   (from the frontend/ directory, with dev server running)
 *
 * This component is safe to mount before that step — the dynamic import
 * simply resolves to nothing if the file does not exist yet.
 */

import { useEffect } from "react";

export function BonesRegistry() {
  useEffect(() => {
    // @ts-ignore — @/bones/registry is generated by `npm run bones`
    import(/* webpackIgnore: true */ "@/bones/registry").catch(() => {
      // Not yet generated — run `npm run bones` after starting the dev server.
    });
  }, []);

  return null;
}
